### ISSUE TITLE
torch can't load models trained on GPUs on CPU only machines

### ISSUE THREAD

**Issue by gallenaxel** [baler-collaboration/baler#242]
**Describe the bug**
When trying to load a .pt model trained on a GPU on a CPU only machine, an error occurs. 

**Expected behavior**
This is expected, and there's an easy fix for it. We need to add an check everytime `torch.load()` is called, and if `torch.cuda.is_available() == False`, add the argument `map_location=torch.device('cpu')` to `torch.load()`.

I can take care of this, but it won't be until May

**Comment by exook** [comment]
@singh96aman , did you have a similar issue to this?

**Comment by singh96aman** [comment]
My previous issues are unrelated to this as I haven't tried training models on GPU and then run on CPU.
This would be a good feature to add and test and raise a PR this week
Thanks!

**Comment by singh96aman** [comment]
As per suggestion, I've added map_location to the destination device to allow for inter-device compatibility between different Baler modes. Tested with training on GPU and compressing with CPU.

Raised a PR - https://github.com/baler-collaboration/baler/pull/276

**Comment by singh96aman** [comment]
PR is merged. This issue is fixed.
